### ISSUE TITLE
my files are empty after conversion

### ISSUE THREAD

**Issue by sede1900** [koshevy/gulp-twig-php#6]
I have a folder structure like this 
src/views/
             default.twig
             test.twig

the content of the files are 
`{# default.twig #}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="description" content="A demo of how to use gulp-twig"/>
    <meta name="author" content="Simon de Turck"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
 
    <title>{{ title }}</title>
 
</head>
<body>
<section>
    {% block page %}{% endblock %}
</section>
</body>
</html>`

and 
`{# test.twig #}

{% extends 'default.twig' %}

{% block page %}
<h1>Hello world</h1>
{% endblock %}`

when I launch the command, I see that the plugin found the templates and it creates my html files in the good folder but the files are empty

Do I have missed something ?

**Comment by ghost** [comment]
having the same problem currently! Does anyone has a solution meanwhile?
